version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ./the_burger_spot.csv:/app/the_burger_spot.csv  
    environment:
      - PORT=8000
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
